apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: podinfo
 namespace: flux-system
spec:
 interval: 5m0s
 path: ./podinfo
 prune: true
 sourceRef:
   kind: GitRepository
   name: k8s-deploy
 targetNamespace: pod-info
