apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: k8s-deploy
 namespace: flux-system
spec:
 interval: 30s
 ref:
   branch: main
 url: https://github.com/souravdinda/k8s-deploy.git
