apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster1
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster1
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-deploy
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster2
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster2
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-deploy
  validation: client
